#!/bin/bash
#Project 3 - CIT470-001
#Logan Toler
#tests client monit config

echo "Installing required packages..." &&
yum -y install stress &&
echo "Packages installed." &&

#Kill SSH
echo "Testing SSH..."
systemctl stop sshd
sleep 60
monit summary | grep SSH

#Kill syslog
echo "Testing syslog..."
systemctl stop rsyslog
sleep 60
monit summary | grep syslog
echo "Syslog testing complete!"

#Kill NFS-Client
echo "Testing NFS client..."
systemctl stop nfs
sleep 60
monit summary | grep NFS-Client
echo "NFS-Client testing complete!"

#Kill LAP-Client
echo "Testing LDAP client..."
systemctl stop nslcd
sleep 60
monit summary | grep LDAP-Client
echo "LDAP-Client testing complete!"
 
#Overload CPU and MEM with stress tool
echo "Testing CPU and memory usage..."
stress --vm-bytes default --cpu 100 --timeout 60
monit summary | grep $HOST
echo "CPU and MEM testing complete!"

#Test hard drive alarm
echo "Testing disk usage.."
dd if=/dev/zero of=/dev/diskhog bs=1M count=1000 >& 1 >> /var/log/client-test.log
sleep 60
monit summary | grep Home ; monit summary | grep Root ; monit summary | grep Var
rm /dev/diskhog -f >& 1 >> /var/log/client-test.log
echo "Disk usage testing complete!"
