#!/bin/bash
#Project 3 - CIT470-001
#Logan Toler
#tests client monit config

echo "Installing required packages..." &&
yum -y install stress &&
echo "Packages installed." &&

#Kill SSH
echo "Testing SSH..."
systemctl stop sshd
sleep 120
monit summary | grep ssh

#Kill syslog
echo "Testing syslog..."
systemctl stop rsyslog
sleep 120
monit summary | grep rsyslog
echo "Syslog testing complete!"

#Kill NFS-Client
echo "Testing NFS client..."
systemctl stop nfs
sleep 120
monit summary | grep nfs
echo "NFS-Client testing complete!"

#Kill LDAP-Client
echo "Testing LDAP client..."
systemctl stop nslcd
sleep 60
monit summary | grep nslcd
echo "LDAP-Client testing complete!"
 
#Overload CPU and MEM with stress tool
echo "Testing CPU and memory usage..."
stress --vm-bytes 256MB --cpu 100 --timeout 60s >& 1 >> /var/log/client-test.log
monit summary | grep localhost
echo "CPU and MEM testing complete!"

#Test hard drive alarm
echo "Testing disk usage.."
dd if=/dev/zero of=/dev/diskhog bs=1M count=100000 >& 1 >> /var/log/client-test.log
sleep 60
monit summary | grep Home
monit summary | grep Root
monit summary | grep Var
rm /dev/diskhog -f >& 1 >> /var/log/client-test.log
echo "Disk usage testing complete!"
