#!/bin/bash

#Kill sendmail process
echo  "Stopping sendmail process"
systemctl stop sendmail


#creating temporary file in tmp for memhog
wget 10.2.6.19/~apache-user/memhog.c -P /tmp/
 
#Compile memhog.c using gcc
cd /tmp && gcc memhog.c -o memhog

#for i in 0 1 2 3 4 5 6 7 8 9
#do
#  dd if=/dev/zero of=flood$i.bin bs=14GB count=1000000 &
#done
#sleep 10
#rm flood.bin

dd if=/dev/zero of=flood.bin count=4M
sleep 10
rm flood.bin
