#!/bin/bash
#Project 3 - CIT470-001
#Logan Toler
#tests server monit config

echo "Installing required packages..." &&
yum -y install stress &&
echo "Packages installed." &&

#Kill SSH
echo "Testing SSH..."
systemctl stop sshd
sleep 120
monit summary | grep ssh

#Kill syslog
echo "Testing syslog..."
systemctl stop rsyslog
sleep 120
monit summary | grep rsyslog

#Kill NFS-Server
echo "Testing NFS client..."
systemctl stop nfs
sleep 120
monit summary | grep nfs
echo "NFS-Server testing complete!"

#Kill LDAP-Server
echo "Testing LDAP client..."
systemctl stop slapd
sleep 120
monit summary | grep slapd
echo "LDAP-Server testing complete!"

#Overload CPU and MEM with stress tool
echo "Testing CPU and memory usage..."
stress --vm-bytes 256MB --cpu 100 --timeout 60s >& 1 >> /var/log/client-test.log
monit summary | grep localhost
echo "CPU and MEM testing complete!"

#Test hard drive alarm
echo "Testing disk usage.."
dd if=/dev/zero of=/dev/diskhog bs=1M count=100000 >& 1 >> /var/log/client-test.log
sleep 60
monit summary | grep Home
monit summary | grep Root
monit summary | grep Var
rm /dev/diskhog -f >& 1 >> /var/log/client-test.log
echo "Disk usage testing complete!"
